<a href="https://colab.research.google.com/github/helloitsdaksh/Tensorflow_colab/blob/main/00_Exercise_Extra_Cirrculum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

#Exercise

In [ ]:
#Q1
scalar = tf.constant(7)
vector = tf.constant([10,7])
matrix = tf.constant([[10,7],
                      [10,7]])
tensor = tf.constant([[[1,2],
                       [3,4]],
                      [[5,6],
                       [6,7]],
                      [[8,9],
                       [10,11]]])

In [ ]:
#Q2
print("tensor shape",tensor.shape)
print("tensor rank",tf.rank(tensor),tensor.ndim)
print("tensor size",tf.size(tensor))

tensor shape (3, 2, 2)
tensor rank tf.Tensor(3, shape=(), dtype=int32) 3
tensor size tf.Tensor(12, shape=(), dtype=int32)


In [ ]:
#Q3
A = tf.random.uniform(shape = (5,300),minval = 0,maxval = 1)
B = tf.random.uniform(shape = (5,300),minval = 0,maxval = 1)
A,B


(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.1538856 , 0.4549483 , 0.80402887, ..., 0.6125461 , 0.7068416 ,
         0.4824468 ],
        [0.6426667 , 0.05918157, 0.25458515, ..., 0.420071  , 0.43640363,
         0.15535128],
        [0.93819857, 0.19780052, 0.26530504, ..., 0.28706765, 0.89047575,
         0.65854025],
        [0.52921593, 0.43451667, 0.664395  , ..., 0.5639123 , 0.25179875,
         0.7786126 ],
        [0.5436133 , 0.96744275, 0.05844784, ..., 0.976236  , 0.45125508,
         0.8581333 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.81713104, 0.1365887 , 0.99175406, ..., 0.7818012 , 0.8166982 ,
         0.4936149 ],
        [0.41392815, 0.39207458, 0.80242443, ..., 0.5223429 , 0.46671855,
         0.5717813 ],
        [0.5355642 , 0.5280869 , 0.41936874, ..., 0.6413101 , 0.9713135 ,
         0.28850675],
        [0.17918706, 0.49355018, 0.81860876, ..., 0.5235604 , 0.19912505,
         0.57007027],
        [0.46668

In [ ]:
#Q4
tf.matmul(A,tf.transpose(B))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.31769 , 78.74727 , 74.931076, 74.32349 , 77.42735 ],
       [73.57678 , 75.39393 , 73.731964, 70.40754 , 71.83294 ],
       [70.74221 , 76.23718 , 71.56707 , 65.38716 , 70.126785],
       [68.12446 , 75.839005, 69.79582 , 68.907295, 68.34266 ],
       [77.51567 , 84.37263 , 79.13223 , 77.786026, 74.81047 ]],
      dtype=float32)>

In [ ]:
#Q5
tf.tensordot(A,tf.transpose(B),axes =1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.31769 , 78.74727 , 74.931076, 74.32349 , 77.42735 ],
       [73.57678 , 75.39393 , 73.731964, 70.40754 , 71.83294 ],
       [70.74221 , 76.23718 , 71.56707 , 65.38716 , 70.126785],
       [68.12446 , 75.839005, 69.79582 , 68.907295, 68.34266 ],
       [77.51567 , 84.37263 , 79.13223 , 77.786026, 74.81047 ]],
      dtype=float32)>

In [ ]:
#Q6
C = tf.random.uniform(shape = (224,224,3),minval = 0,maxval = 1)
C

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.89615834, 0.44361675, 0.78707397],
        [0.5242789 , 0.25289333, 0.95354664],
        [0.21082139, 0.3101195 , 0.29795146],
        ...,
        [0.4956187 , 0.24129534, 0.7836689 ],
        [0.5854957 , 0.04060555, 0.35518897],
        [0.15043116, 0.5437859 , 0.43495703]],

       [[0.47579312, 0.03967166, 0.5838301 ],
        [0.17238486, 0.26102698, 0.49317086],
        [0.9293479 , 0.41040933, 0.5939598 ],
        ...,
        [0.65666115, 0.5561148 , 0.61246   ],
        [0.5641688 , 0.6057303 , 0.88049495],
        [0.13707411, 0.44519544, 0.79492486]],

       [[0.06625557, 0.82375133, 0.06577992],
        [0.68053985, 0.990962  , 0.5248904 ],
        [0.7523068 , 0.5261034 , 0.9915445 ],
        ...,
        [0.84605455, 0.221933  , 0.3193121 ],
        [0.8618599 , 0.31575406, 0.42587042],
        [0.21533322, 0.19134855, 0.8473387 ]],

       ...,

       [[0.8716239 , 0.29909873, 0.054932  ],
        [0.76

In [ ]:
#Q7
tf.reduce_max(C,axis = 0),tf.reduce_min(C,axis =0)

(<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
 array([[0.99778616, 0.9999051 , 0.99364364],
        [0.98921144, 0.99573755, 0.9961163 ],
        [0.9970943 , 0.99397135, 0.99434257],
        [0.9994211 , 0.9971347 , 0.99922216],
        [0.99787104, 0.9950768 , 0.99446964],
        [0.9972873 , 0.99272704, 0.996781  ],
        [0.99801826, 0.99984396, 0.9971806 ],
        [0.9938588 , 0.995994  , 0.9965118 ],
        [0.99884903, 0.9986614 , 0.9988743 ],
        [0.9901539 , 0.99986017, 0.9989308 ],
        [0.9980409 , 0.9987749 , 0.99433815],
        [0.9949528 , 0.9959458 , 0.99267066],
        [0.9963517 , 0.99558914, 0.99445724],
        [0.9884    , 0.9751797 , 0.99155533],
        [0.99879754, 0.9966862 , 0.9933183 ],
        [0.993255  , 0.9865228 , 0.9949752 ],
        [0.9979509 , 0.98626745, 0.9984307 ],
        [0.9987899 , 0.9935298 , 0.9999583 ],
        [0.999352  , 0.9931226 , 0.99815655],
        [0.9923117 , 0.9951658 , 0.9974196 ],
        [0.9991834 , 0.997423

In [ ]:
#Q8
E = tf.random.normal(shape = (1,224,224,3))
D = tf.squeeze(E)
D.shape

TensorShape([224, 224, 3])

In [ ]:
#Q9
F = tf.constant(np.arange(10))
tf.argmax(F).numpy()

9

In [ ]:
#Q10
tf.one_hot(F,depth = 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

#EXTRA-CIRRCULUM

In [ ]:
#Part 1
tf.math.logical_not(tf.constant([True, False]))


<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False,  True])>

In [ ]:
#Part 2 shape(x,y,z) 
#x = years
#y = months
#z = no.of items
G = tf.constant(np.array([np.random.randint(0,50,(12,5))]),shape = (1,12,5))
G

<tf.Tensor: shape=(1, 12, 5), dtype=int64, numpy=
array([[[36, 20, 26, 41, 31],
        [49, 39,  1,  2,  8],
        [49, 19,  6, 29, 24],
        [ 8,  4,  2, 43, 12],
        [32, 36,  3, 13, 33],
        [30, 22, 43,  4, 43],
        [15, 40, 19, 41, 31],
        [23, 28, 38, 22, 43],
        [39,  8, 37, 38,  7],
        [ 2, 15, 14, 24, 29],
        [ 7,  7,  8, 17,  7],
        [ 6, 46, 32, 35, 22]]])>

In [ ]:
#sum of months
sum_month = tf.reduce_sum(G,axis = 2)
sum_month.numpy()

array([[154,  99, 127,  69, 117, 142, 146, 154, 129,  84,  46, 141]])

In [ ]:
sum_year = tf.reduce_sum(sum_month)
sum_year.numpy()

1408