<a href="https://colab.research.google.com/github/helloitsdaksh/Tensorflow_colab/blob/main/00_fundamentals_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##BASIC OF TENSORFLOW



##Introduction to Tensors


In [2]:
import tensorflow as tf
tf.__version__

'2.5.0'

### Using `tf.constant()` function


In [3]:
#tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#scalar has no dimension
scalar.ndim

0

In [5]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
#vector has dimension which is equal to 1.
vector.ndim

1

In [7]:
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
#matrix has dimension equal to 2
matrix.ndim

2

In [9]:
another_matrix = tf.constant([[10,7],[7,10]],dtype = 'float16')
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.]], dtype=float16)>

In [10]:
tensor  =  tf.constant([[[1,2],
                         [3,4]],
                        [[5,6],
                         [6,7]],
                        [[8,9],
                         [10,11]]])
tensor 

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]], dtype=int32)>

In [11]:
tensor.ndim

3

All of the above variables we've created are actually tensors. But you may also hear them referred to as their different names (the ones we gave them):

* scalar: a single number.
* vector: a number with direction (e.g. wind speed with direction).
* matrix: a 2-dimensional array of numbers.
* tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).

To add to the confusion, the terms matrix and tensor are often used interchangably.

###Creating Tensors with `tf.Variable()`

In [12]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [13]:
 changeable_tensor = tf.Variable([10,7])
 unchangeable_tensor = tf.constant([10,7])

 changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# Let's try to change one of the element in our changeable tensor using .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating Random Tensors

In [15]:
 random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibitlity
 random_1 = tf.random.normal(shape = (3,2))

 random_2 = tf.random.uniform(shape = (3,2))
 random_1,random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.4909813 , -1.091538  ],
        [-2.1554897 , -0.6853175 ],
        [-0.48683265, -1.1284212 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.32725513, 0.37229657],
        [0.34030414, 0.05685222],
        [0.8159386 , 0.6628939 ]], dtype=float32)>)

### Shuffle the order of elements in a tensor

In [16]:
#shuffle a tensor
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [5,6]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 5,  6]], dtype=int32)>

In [17]:
shuffled = tf.random.shuffle(not_shuffled,seed = 10) #operational 
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 5,  6]], dtype=int32)>

In [18]:
#this is a global seed set on the random function not on shuffle function hence gives same output everytime
tf.random.set_seed(10) #global
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  6],
       [ 3,  4]], dtype=int32)>

### Other ways to create tensors

In [19]:
tf.zeros(shape = (3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [20]:
tf.ones(shape = (3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

### Turn numpy arrays into Tensors

In [21]:
import numpy as np
numpy_A = np.arange(1,25)
numpy_A

# X = tf.constant(some_matrix)
# y = tf.constant(vector)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [22]:
tf.constant(numpy_A)

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [23]:
#reshapeing the numpy array
tf.constant(numpy_A,shape = (2,3,4))
# 2*3*4 = number of elements in the numpy_A

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

### Getting information form tensors
* shape
* rank
* axis or dimension
* Size


In [24]:
rank_4_tensor = tf.zeros(shape = (2,3,4,5,))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
rank_4_tensor[0],rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
 array([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=float32)>,
 TensorShape([2, 3, 4, 5]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [26]:
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) 

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


### Indexing tensors

#### Tensors can be indexed just like Python lists

In [27]:
# Get the first 3 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [28]:
# Get the dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [29]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

#### You can also add dimensions to your tensor whilst keeping the same information present using tf.newaxis.

In [30]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to"
rank_2_tensor, rank_3_tensor # shape (2, 2), shape (2, 2, 1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [31]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [32]:
tf.expand_dims(rank_2_tensor,axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensors(tensor operation)

**Basic Operation**
`+`,`-`,`*`,`/`

In [33]:
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [34]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [35]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [36]:
tensor / 5

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2. , 1.4],
       [0.6, 0.8]])>

In [37]:
# using tensorflow built in commands
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [38]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

**MATRIX MULTIPLICATION**

The main two rules for matrix multiplication to remember are:

1. The inner dimensions must match:
  * (3, 5) @ (3, 5) won't work
  * (5, 3) @ (3, 5) will work
  * (3, 5) @ (5, 3) will work
2. The resulting matrix has the shape of the outer dimensions:
  * (5, 3) @ (3, 5) -> (5, 5)
  * (3, 5) @ (5, 3) -> (3, 3)

In [39]:
#matrix multiplication in tensorflow
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [40]:
#matrix multiplication with python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [41]:
tensor_A = tf.constant([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = tf.constant([[7,8],
                        [9,10],
                        [11,12]])
tf.matmul(tensor_A,tf.transpose(tensor_B))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [42]:
# or method
tf.reshape(tensor_B,shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [43]:
tensor_A @ tf.reshape(tensor_B,shape = (2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [44]:
tf.matmul(tf.transpose(tensor_A),tensor_B)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**Transpose is not equal to Reshape**





**The Dot Product**

Matrix Multiplication is also called the dot product.
* `tf.matmul()`
* `tf.tensordot`

In [45]:
tensor_A,tensor_B

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [46]:
tf.tensordot(tf.transpose(tensor_A),tensor_B, axes = 1 )

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [47]:
tf.matmul(tensor_A, tf.transpose(tensor_B))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [48]:
tf.matmul(tensor_A, tf.reshape(tensor_B, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [49]:
tensor_B.shape, tf.reshape(tensor_B, (2, 3)).shape, tf.transpose(tensor_B).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [50]:
print("Normal Y:")
print(tensor_B, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(tensor_B, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(tensor_B))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


**Generally, when performing matrix multiplication on two tensors and one of the axis doesnt line up, ypu will transpose to get the satisify matrix multiplication rules**

###Changing data type of tensor

`tf.cast()`

In [51]:
tensor_A

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [52]:
tf.cast(tensor_A,dtype= 'float16')

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [53]:
tensor_A.dtype

tf.int32

###Aggregating Tensors
Aggregating  = condesing them to form multpile values down to a smaller amount of values

In [54]:
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [55]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>


Finding the min, max, mean, sum (aggregation)
You can quickly aggregate (perform a calculation on a whole tensor) tensors to find things like the minimum value, maximum value, mean and sum of all the elements.

To do so, aggregation methods typically have the syntax reduce()_[action], such as:

* tf.reduce_min() - find the minimum value in a tensor.
* tf.reduce_max() - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).
* tf.reduce_mean() - find the mean of all elements in a tensor.
* tf.reduce_sum() - find the sum of all elements in a tensor.
* Note: typically, each of these is under the math module, e.g. tf.math.reduce_min() but you can use the alias tf.reduce_min().
Let's see them in action.

In [56]:
X = tf.random.normal(shape = (3,2),seed = 40)
X

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.14618911,  0.33093095],
       [ 1.0759188 ,  1.7531368 ],
       [ 0.5442372 ,  0.2526686 ]], dtype=float32)>

In [57]:
tf.reduce_min(X).numpy()

-0.14618911

In [58]:
tf.reduce_max(X).numpy()

1.7531368

In [59]:
tf.reduce_mean(X).numpy()

0.6351172

In [60]:
tf.reduce_sum(X).numpy()

3.810703

In [61]:
tf.math.reduce_std(X).numpy()

0.6193772

In [62]:
tf.math.reduce_variance(X).numpy()

0.3836281

### Find a Positional maximum or minimum

In [63]:
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.55478156, 0.42658198, 0.14140713, 0.703694  , 0.3726666 ,
       0.6976985 , 0.23352468, 0.5646274 , 0.19849169, 0.9528502 ,
       0.50030744, 0.21903634, 0.8735709 , 0.7988689 , 0.23574066,
       0.9717263 , 0.39008486, 0.31639826, 0.7967795 , 0.98036146,
       0.5515257 , 0.873881  , 0.24983549, 0.22227013, 0.08600712,
       0.55661273, 0.339512  , 0.79473007, 0.6598681 , 0.71315587,
       0.59639835, 0.5791054 , 0.14415431, 0.553211  , 0.01565135,
       0.38739872, 0.7419901 , 0.09770393, 0.9472481 , 0.45996988,
       0.37026238, 0.04783547, 0.68970215, 0.62162685, 0.8883996 ,
       0.36960876, 0.20806956, 0.65597486, 0.17572486, 0.22346973],
      dtype=float32)>

In [64]:
tf.argmax(F)


<tf.Tensor: shape=(), dtype=int64, numpy=19>

In [65]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.98036146>

In [66]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=34>

In [67]:
F[tf.argmin(F).numpy()]

<tf.Tensor: shape=(), dtype=float32, numpy=0.015651345>

###Squeezing a tesnor (removing all single dimension)

In [68]:
G = tf.constant(tf.random.uniform(shape= (50,)),shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.28776777, 0.53159165, 0.6660836 , 0.43517685, 0.2712083 ,
           0.8262744 , 0.41320777, 0.62144256, 0.5367851 , 0.96463275,
           0.6266488 , 0.89379966, 0.75270236, 0.38672495, 0.45730412,
           0.7238827 , 0.64191616, 0.95943916, 0.57779634, 0.2630353 ,
           0.94205904, 0.65421   , 0.38572538, 0.44459426, 0.09028375,
           0.54862213, 0.36923027, 0.07785499, 0.01096857, 0.7239616 ,
           0.8035939 , 0.9998133 , 0.3602084 , 0.5360074 , 0.65006006,
           0.51131487, 0.0583415 , 0.3275509 , 0.90608835, 0.5725883 ,
           0.6773243 , 0.36113596, 0.9224639 , 0.20634818, 0.87863517,
           0.7900193 , 0.65320325, 0.14117801, 0.94063306, 0.70207703]]]]],
      dtype=float32)>

In [69]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [70]:
G_squeezed = tf.squeeze(G)
G_squeezed , G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.28776777, 0.53159165, 0.6660836 , 0.43517685, 0.2712083 ,
        0.8262744 , 0.41320777, 0.62144256, 0.5367851 , 0.96463275,
        0.6266488 , 0.89379966, 0.75270236, 0.38672495, 0.45730412,
        0.7238827 , 0.64191616, 0.95943916, 0.57779634, 0.2630353 ,
        0.94205904, 0.65421   , 0.38572538, 0.44459426, 0.09028375,
        0.54862213, 0.36923027, 0.07785499, 0.01096857, 0.7239616 ,
        0.8035939 , 0.9998133 , 0.3602084 , 0.5360074 , 0.65006006,
        0.51131487, 0.0583415 , 0.3275509 , 0.90608835, 0.5725883 ,
        0.6773243 , 0.36113596, 0.9224639 , 0.20634818, 0.87863517,
        0.7900193 , 0.65320325, 0.14117801, 0.94063306, 0.70207703],
       dtype=float32)>, TensorShape([50]))

###One Hot encoding Tensors

In [71]:
some_list = [0,1,2,3]
tf.one_hot(some_list, depth = 4) #depth is the total number of distinct numbers

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [72]:
tf.one_hot(some_list, depth = 4, on_value='True', off_value='False')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'True', b'False', b'False', b'False'],
       [b'False', b'True', b'False', b'False'],
       [b'False', b'False', b'True', b'False'],
       [b'False', b'False', b'False', b'True']], dtype=object)>

### Squaring, Log, Square root

In [73]:
H = tf.range(10)
H

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [74]:
tf.square(H)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [75]:
tf.sqrt(tf.cast(H,dtype = 'float32'))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.236068 ,
       2.4494898, 2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [76]:
tf.math.log(tf.cast(H, dtype = 'float32'))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([     -inf, 0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 ,
       1.7917595, 1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

In [77]:
J = tf.constant(np.array([3,7,10]))
J

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([ 3,  7, 10])>

In [78]:
np.array(J)

array([ 3,  7, 10])

###Finding  access to GPU

In [79]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [81]:
!nvidia-smi

Wed Jun  9 20:08:42 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.27       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P0    27W /  70W |    224MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

**If you have access to CUDA-enabled GPu, Tensorflow will automactically use it as per the requirements**